version: 0.2

phases:
  install:
    commands:
      - npm i
  pre_build:
    commands:
      - npm run re
  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/**/*
  name: build-$(date +%Y-%m-%d)
